const {chromium}=require('C:/Users/adolf/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs');const assert=require('node:assert/strict');
const base=process.env.TEST_URL||'http://127.0.0.1:4322';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const results=[];try{
 for(const width of (process.env.VERIFY_ROUTES_ONLY ? [] : [320,375,390,768,1024,1440,2527])){const context=await browser.newContext({viewport:{width,height:width>2000?1229:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base,{waitUntil:'networkidle'});await page.locator('astro-dev-toolbar').evaluateAll(els=>els.forEach(e=>e.remove()));await page.keyboard.press('Tab');assert(await page.locator('.skip').evaluate(e=>e===document.activeElement),'skip focus');await page.keyboard.press('Enter');await page.mouse.click(width-5,400);
 for(const id of ['inicio','vision','pacto','pacto-vivido','nos-vemos']){await page.locator(`.story-progress a[href="#${id}"]`).click();await page.waitForTimeout(1100);const state=await page.locator(`#${id}`).evaluate(e=>({top:e.getBoundingClientRect().top,inert:e.inert,visible:getComputedStyle(e).opacity,overflow:document.documentElement.scrollWidth>innerWidth,header:document.querySelector('header').offsetHeight}));assert(!state.inert&&!state.overflow,`${width} ${id} ${JSON.stringify(state)}`);assert(state.top>=state.header-3,`heading obscured ${width} ${id} ${state.top}`);assert.equal(await page.locator('.story-progress a[aria-current=step]').getAttribute('href'),`#${id}`);if(width===390||width===1440)await page.screenshot({path:`evidencia/final-${width}-${id}.png`});}
 await page.goto(base,{waitUntil:'networkidle'});await page.locator('astro-dev-toolbar').evaluateAll(els=>els.forEach(e=>e.remove()));await page.waitForTimeout(800);if([390,1440,2527].includes(width))await page.screenshot({path:`evidencia/final-${width}-inicio.png`});
 if(width<1021){const menu=page.locator('.community-menu-toggle');await menu.click();assert.equal(await menu.getAttribute('aria-expanded'),'true');assert(await page.locator('main').evaluate(e=>e.inert));await page.keyboard.press('Shift+Tab');assert(await menu.evaluate(e=>document.activeElement===e));await page.keyboard.press('Shift+Tab');assert(await page.locator('#mobile-nav a').last().evaluate(e=>document.activeElement===e));if(width===390)await page.screenshot({path:'evidencia/final-menu-movil.png'});await page.keyboard.press('Escape');assert.equal(await menu.getAttribute('aria-expanded'),'false');assert(await menu.evaluate(e=>document.activeElement===e));await menu.click();await page.locator('#mobile-nav').getByRole('link',{name:/Nuestro pacto/}).click();await page.waitForTimeout(1000);assert(await page.locator('#mobile-nav').evaluate(e=>e.hidden));assert(!await page.locator('main').evaluate(e=>e.inert));assert.equal(new URL(page.url()).hash,'#pacto');}
 assert.equal(errors.length,0,errors.join('\n'));assert.equal(await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||!i.naturalWidth).length),0);results.push({width,status:'PASS',checks:'overflow, images, five anchors, active progress, keyboard, mobile menu, JS errors'});console.log(width+'px PASS');await context.close();}
 const c=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});const p=await c.newPage();await p.goto(base,{waitUntil:'networkidle'});assert.equal(await p.locator('html').evaluate(e=>getComputedStyle(e).scrollBehavior),'auto');assert.equal(await p.locator('.community-liquid').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await p.locator('.reveal').first().evaluate(e=>getComputedStyle(e).opacity),'1');await p.emulateMedia({reducedMotion:'no-preference'});await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.community-liquid').evaluate(e=>getComputedStyle(e).transform),'none');
 for(const route of ['/agenda/','/blog/','/primera-vez/','/contacto/','/quienes-somos/','/que-hacemos/']){const r=await p.goto(base+route,{waitUntil:'networkidle'});assert.equal(r.status(),200);assert.equal(await p.locator('main h1').count(),1);assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));}results.push({status:'PASS',checks:'reduced motion, live preference changes, six routes'});await c.close();
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const n=await nojs.newPage();await n.goto(base);assert.equal(await n.locator('.reveal').first().evaluate(e=>getComputedStyle(e).opacity),'1');results.push({status:'PASS',checks:'no JavaScript content visibility'});await nojs.close();fs.writeFileSync('evidencia/verificacion-movimiento.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
